# Generated by Django 2.1.7 on 2019-03-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='datafile',
            new_name='file',
        ),
    ]
